name: Learning React Workflow

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint-html:
    name: Lint HTML Files
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install HTML Linter
        run: npm install -g htmlhint

      - name: Run HTML Linter
        run: htmlhint "**/*.html"

  summarize-technologies:
    name: Tecnolgias Utilizadas no Projeto
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Summarize Technologies
        run: |
          echo "Technologies used in this project:"
          echo "- React"
          echo "- Node.js"
          echo "- HTML"
          echo "- GitHub Actions"
