name: Learning React Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:    
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install HTML Validator
      run: npm install html-validator-cli

    - name: Validação do HTML
      run: npx html-validator --file=index.html --verbose

  lint-html:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

      run: |
        npm install --save-dev htmlhint
        npm install -g htmlhint

    - name: Lint HTML
      run: htmlhint index.html    