name: CI Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:    
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Validate HTML
      uses: chrisderv/validate-html-action@v1
      with:
        files: |
          index.html
 
