name: Learning React Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint-html:
    name: Lint HTML
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install HTMLHint
        run: npm install -g htmlhint

      - name: Run HTML Linter
        run: htmlhint "**/*.html"
